In [3]:
import math
import numpy as np
import pandas as pd

In [18]:
window_size = 10
data = pd.read_parquet('resultadoIndicadores.parquet')
data = data.drop(['EMA_5','EMA_63', 'EMA_63', 'WMA_63', 'MINUS_DM','PLUS_DI', 'AD', 'WMA_5'], axis=1)

In [20]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))


def state_creator(data, timestep, window_size):
  
  # starting day of our state
  starting_id = timestep - window_size + 1
  
  if starting_id >= 0:
    windowed_data = data[starting_id:timestep+1]
  else:
    # Replicate member (data[0]) needed times
    windowed_data = - starting_id * [data.iloc[0]] + list(data[0:timestep+1])
    
  state = []
  # Iterate trough whole windowed_data minus current state (-1)
  for i in range(window_size - 1):
    # Normalize the difference from current day and the next day
    # Because the prices can be very different and we want them on same scale
    state.append(sigmoid(windowed_data[i+1] - windowed_data[i]))
    
  return np.array([state])

In [ ]:
def state_creator(data, timestep, window_size):
  
  # starting day of our state
  starting_id = timestep - window_size + 1
  
  if starting_id >= 0:
    windowed_data = data[starting_id:timestep+1]
  else:
    # Replicate member (data[0]) needed times
    windowed_data = - starting_id * [data[0]] + list(data[0:timestep+1])
    
  state = []
  # Iterate trough whole windowed_data minus current state (-1)
  for i in range(window_size - 1):
    # Normalize the difference from current day and the next day
    # Because the prices can be very different and we want them on same scale
    state.append(sigmoid(windowed_data[i+1] - windowed_data[i]))
    
  return np.array([state])

In [61]:
state = []
for i in range(1):
    state.append(sigmoid(data['SMA_5'][i+1] - data['SMA_5'][i]))
    state.append(sigmoid(data['SMA_21'][i+1] - data['SMA_21'][i]))
    state.append(sigmoid(data['SMA_63'][i+1] - data['SMA_63'][i]))
    state.append(sigmoid(data['EMA_21'][i+1] - data['EMA_21'][i]))
    state.append(sigmoid(data['WMA_21'][i+1] - data['WMA_21'][i]))
    state.append(sigmoid(data['middle'][i+1] - data['middle'][i]))
    state.append(sigmoid(data['PLUS_DM'][i+1] - data['PLUS_DM'][i]))
    state.append(sigmoid(data['MINUS_DI'][i+1] - data['MINUS_DI'][i]))
    state.append(sigmoid(data['SAR'][i+1] - data['SAR'][i]))
    state.append(sigmoid(data['ADX'][i+1] - data['ADX'][i]))

np.array([state])


array([[0.45894275, 0.33071239, 0.48109581, 0.54126934, 0.59265915,
        0.54929343, 0.08595002, 0.35559431, 0.77157366, 0.20149962]])

In [ ]:
next_state = state_creator(data=data, timestep=(t + 1), window_size=(9 + 1))

In [90]:
sigmoid(data.iloc[-1 + 1:0 +1, 0:10].values - data.iloc[+:1 + 1, 0:10].values)

array([[0.68992291, 0.36041518, 0.48326228, 0.50613504, 0.57766267,
        0.51177573, 0.76287913, 0.44332014, 0.31945996, 0.2632473 ]])

In [107]:
time = 0
window_size = 10

state = []
state.append(sigmoid(data.iloc[time:time + 1, :10].values - data.iloc[time -1 :time, :10].values))

    
np.array([state])


array([], shape=(1, 1, 0, 10), dtype=float64)

In [110]:
sigmoid(data.iloc[time:time + 1, :10].values)

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.99999996, 1.        ]])

In [131]:
timestemp = 15
window_size = 10 # Numero de indicadores

In [132]:
def state_indicador_creator(data, timestemp, window_size):

    state = []
    if timestemp == 0:
        state.append(sigmoid(data.iloc[0:1, :window_size].values - data.iloc[0:1, :window_size].values))
    else:
        state.append(sigmoid(data.iloc[timestemp:timestemp + 1, :window_size].values - data.iloc[timestemp -1 :timestemp, :window_size].values))

    return np.array([state])

In [133]:
state_indicador_creator(data, timestemp, window_size)

array([[[[0.25194034, 0.74347938, 0.51979271, 0.62482017, 0.67782139,
          0.6243827 , 0.80184812, 0.29270485, 0.32418882, 0.37890178]]]])

In [112]:
state.append(sigmoid(data.iloc[time:time + 1, :10].values - data.iloc[time -1 :time, :10].values))

In [113]:
sigmoid(data.iloc[0:1, :10].values - data.iloc[0:1, :10].values)

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])